### ISSUE TITLE
How to convert hair to obj or fbx ?

### ISSUE THREAD

**Issue by Michaelwhite34** [BernhardEgger/USC-HairSalon-python#1]

**Comment by BernhardEgger** [comment]
Hi, 

I don't see how this question is related to this repository, but to celebrate how awesome Thursdays are I want to help you anyways:

I think meshlab can do that.
You can also use meshlabserver if you want to script it.

:)

Best
Bernhard

**Comment by Michaelwhite34** [comment]
> Hi,
> 
> I don't see how this question is related to this repository, but to celebrate how awesome Thursdays are I want to help you anyways:
> 
> I think meshlab can do that. You can also use meshlabserver if you want to script it.
> 
> :)
> 
> Best Bernhard

I just found a blender script to directly import these data files, thanks for the reply though.
